name: CI/CD for time-app project

on:
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    if: github.event_name == "push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.19.3"]
    steps:
      - name: Cloning repository
        uses: actions/checkout@v6

      - name: Install Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}
      
      - name: API Dependency Install
        working-directory: ./api
        run: npm install

      - name: API unit test
        working-directory: ./api
        run: npm run test
      
      - name: Frontend Dependency Install
        working-directory: ./frontend
        run: npm install

  docker-image-build-and-push:
    if: github.event_name == "push"
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses: actions/checkout@v6

      - name: Docker login
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: API image build and push to docker hub
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/tmapi ./api
          docker push ${{secrets.DOCKER_USERNAME}}/tmapi
      
      - name: Frontend image build and push to docker hub
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/tmfront ./frontend
          docker push ${{secrets.DOCKER_USERNAME}}/tmfront
  
  deploy-to-aws-vm:
    if: github.event_name == "workflow_dispatch"
    runs-on: ubuntu-latest

    steps:
      - name: AWS VM deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.AWS_VM_HOST}}
          username: ${{secrets.AWS_VM_USERNAME}}
          key:  ${{secrets.AWS_VM_SSH_KEY}}
          port: 22

          script: |
            if [ ! -d "deploy_FSDE_Oct_24_3_ru/.git" ]; then
            git clone https://github.com/Zamanof/deploy_FSDE_Oct_24_3_ru.git
            fi

            cd deploy_FSDE_Oct_24_3_ru
            git pull origin main
            docker compose pull
            docker compose down
            docker compose up -d
            docker image prune -f